Header value required to be a string
```start_response``` requires that headers titles and values are always strings https://github.com/gevent/gevent/blob/master/gevent/pywsgi.py#L740

In other case this code emit exception
```
UnicodeError: ('The value must be a native string', 'Access-Control-Max-Age', 3600)
<Greenlet at 0x10de6e410: _close_when_done(<socket at 0x10e8f0490 fileno=[Errno 9] Bad file d, ('127.0.0.1', 65126))> failed with UnicodeError
```